blog:
  # 索引库存储路径
  index-path: /home/chenjianlink/testEnviornment/lucene
  # 前台分页显示每页总数
  rows: 10
  # 使用的加密算法
  algorithmName: md5
  # 加密迭代次数
  iterations: 4
  # shiroSession过期时间(4*60*60*1000)
  sessionTimeOut: 14400000
  # http端口号
  port: 8080
  # 静态资源绝对路径
  staticPath: /home/chenjianlink/testEnviornment/static/
  # 头像上传绝对路径
  userImagesPath: /home/chenjianlink/testEnviornment/static/userImages/
  # 接收邮件邮箱
  email: chenjianlink1998@gmail.com
  # 聚合数据的IP认证key
  ipKey:
spring:
  # 缓存配置
  cache:
    ehcache:
      config: classpath:cache/ehcache.xml

  # 页面设置
  thymeleaf:
    cache: false

  #　数据库配置
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&allowMultiQueries=true
      username: chenjian
      password: 123456
      # 数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      aop-patterns: cn.chenjianlink.blogv2.controller.*,cn.chenjianlink.blogv2.mapper.*,cn.chenjianlink.blogv2.service.*,cn.chenjianlink.blogv2.exceptionhandler.*

      # druid监控登录
      loginUsername: admin
      loginPassword: 123456

  # 设置编码,避免乱码
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  # 设置文件上传大小
  servlet:
    multipart:
      max-file-size: 5MB

  # 配置静态资源访问
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${blog.staticPath}

  # 邮件设置
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    username:
    password:
    port: 465
    properties:
      mail:
        debug: false
        smtp:
          auth: true  # 需要验证登录名和密码
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        starttls:
          enable: true  # 需要TLS认证 保证发送邮件安全验证
          required: true

# mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatisConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: cn.chenjianlink.blogv2.pojo

# 服务器配置
server:
  #端口号
  port: 8443
  servlet:
    session:
      timeout: 14400s
  tomcat:
    uri-encoding: UTF-8
    #最大并发数
    max-threads: 100
    #接受和处理的最大连接数
    max-connections: 500
    #初始化时创建的线程数
    min-SpareThreads: 30
    #可以放到处理队列中的请求数
    acceptCount: 200
  # SSL配置
  ssl:
    key-store: classpath:ssl/tomcat.keystore
    key-store-password: 123456
    key-store-type: JKS
    enabled: true

# 日志配置
logging:
  file: /home/chenjianlink/testEnviornment/log/blog.log

# shiro配置
shiro:
  loginUrl: /admin/blogger/admin-login
  unauthorizedUrl: /homepage
  kickoutUrl: /admin/blogger/admin-login




